[tools]
deno = "2.5.6"
gleam = "1.13.0"
node = "25.2.1"

[vars]
public_dir = "public"

[tasks.create_public_dir]
run = "mkdir -p {{vars.public_dir}}"
wait_for = ["clean"]

[tasks."compile:index"]
run = "gleam run -m stl_map/build/index"

[tasks."copy:index"]
depends = ["create_public_dir", "compile:index"]
run = "cp dist/index/index.html {{vars.public_dir}}/index.html"

[tasks."compile:routes"]
run = "gleam run -m stl_map/build/routes"

[tasks."copy:routes"]
depends = ["create_public_dir", "compile:routes"]
run = [
    "mkdir -p {{vars.public_dir}}/routes",
    "cp dist/routes/* {{vars.public_dir}}/routes"
]

[tasks."compile:js"]
run = "gleam run -m stl_map/build/js"

[tasks."copy:js"]
depends = ["create_public_dir", "compile:js"]
run = [
    "mkdir -p {{vars.public_dir}}/js",
    "cp dist/js/index2.js* {{vars.public_dir}}/js/"
]

[tasks."dev_js"]
run = [
    "rm -rf {{vars.public_dir}}",
    "mkdir -p {{vars.public_dir}}",
    "gleam build",
    "cd build/dev/javascript && rsync -r -f '+ *.mjs' -f '+ *.js' -f '+ **/' -f '- *' --prune-empty-dirs . ../../../{{vars.public_dir}}/js",
    "echo 'export * from \"./stl_map/stl_map/frontend/index2.mjs\"' > {{vars.public_dir}}/js/index2.js"
]
depends_post = ["copy:static_assets"]

[tasks."copy:static_assets"]
depends = ["create_public_dir"]
run = "cp -r static_assets/* {{vars.public_dir}}"

[tasks.clean]
run = "rm -rf {{vars.public_dir}}"

[tasks.build]
depends = ["clean"]
depends_post = ["copy:index", "copy:routes", "copy:static_assets", "copy:js"]

[tasks.serve]
run = "gleam run -m stl_map/serve"
